name: pokemon_pipeline_3

on:
  push:
    branches:
    - main
        
jobs:
  deployment_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy to dev
        run: echo "Deploying to dev"
      - name: Run a one-line script
        run: echo "Hello there!"
  deployment_prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to prod
        run: echo "Deploying to prod"
      - name: Run a one-line script
        run: echo "Hello there!"
