name: pokemon_pipeline_3

permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches:
    - main
  workflow_call:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: string
        
jobs:
  deployment:
    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Deploy to ${{ inputs.env }}
        run: echo "Deploying to ${{ inputs.env }}"
      - name: Run a one-line script
        run: echo "Hello, ${{ github.event.inputs.environment }}!"
